serverAddr = "服务器的公网IP"
serverPort = 7000

# 配置Token鉴权，要与服务端一致
auth.method = "token"
auth.token = "xxx"

[[proxies]]
name = "server"
type = "tcp"
localIp = "host.docker.internal"
localPort = 8000
remotePort = 8009

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "host.docker.internal"
localPort = 22
remotePort = 10022
